//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        public int id_libro { get; set; }
        public Nullable<int> id_autor { get; set; }
        public string titulo { get; set; }
        public string fecha_lanz { get; set; }
        public string editorial { get; set; }
        public string idioma { get; set; }
        public string paginas { get; set; }
        public byte[] portada { get; set; }
    }
}
